env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - "plugin:react-hooks/recommended"
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules: 
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
  react/display-name: 0
  react/prop-types: 0
  
