name: Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      # - uses: google/ko@main -> This should replace the 2 lines below, but doesn't seem to work
      - run: |
          curl -L https://github.com/google/ko/releases/download/v0.8.3/ko_0.8.3_Linux_x86_64.tar.gz | sudo tar xzf - ko
          chmod +x ./ko
        working-directory:
          /usr/local/bin
      - run: ko login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      - run: yarnpkg --pure-lockfile
      - run: yarnpkg build
      - run: yarnpkg lint
      - run: yarnpkg test
      - run: ko publish -B ./cmd/dsadmin
        env:
          KO_DOCKER_REPO: ghcr.io/remko